name = "dogleg-f"
version = "0.1.0"
license = "LGPL-3.0-or-later"
maintainer = "ivan.pribec@gmail.com"
author = "Ivan Pribec"
copyright = "Copyright 2022 Ivan Pribec"
description = "Fortran interface to libdogleg - general purpose optimizer"
categories = ["io"]
keywords = ["hdf5", "mpi"]
homepage = "https://stdlib.fortran-lang.org"


[build]
auto-executables = false
auto-examples = false
auto-tests = false
link = ["cholmod", "suitesparseconfig", "lapack", "m"]

[[executable]]
name = "sample"
source-dir = "example"
main = "sample.f90"