name = "dogleg-f"
version = "0.1.0"
license = "LGPL-3.0-or-later"
maintainer = "ivan.pribec@gmail.com"
author = "Ivan Pribec"
copyright = "Copyright 2022 Ivan Pribec"
description = "Fortran interface to libdogleg - a large-scale general purpose optimizer"

[build]
auto-executables = false
auto-examples = false
auto-tests = false
link = ["cholmod", "suitesparseconfig", "lapack", "m"]

[[executable]]
name = "sample"
source-dir = "example"
main = "sample.f90"

[[executable]]
name = "powell"
source-dir = "example"
main = "powell.f90"

[[executable]]
name = "lmder_example"
source-dir = "example"
main = "lmder_example.f90"

[[executable]]
name = "mathworks_example"
source-dir = "example"
main = "mathworks_example.f90"